// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SmartAnalytics.Entities.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddParentCodeField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddParentCodeField));
        
        string IMigrationMetadata.Id
        {
            get { return "201507140955360_AddParentCodeField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
